import React from 'react'
import { Link } from 'react-router-dom'
import {
  Bot,
  ChartColumnIncreasing,
  CreditCard,
  FileText,
  PackageSearch,
  ReceiptText,
  ShieldCheck,
  Sparkles,
  Workflow,
} from 'lucide-react'

const featureCards = [
  {
    title: 'Conversational AI Shopping Assistant',
    description: 'Customers can ask for products in natural language and get guided buying help instead of hunting through filters.',
    icon: Bot,
  },
  {
    title: 'Smart Recommendations',
    description: 'The agent compares options, suggests the best fit, and keeps cost and availability visible before checkout.',
    icon: PackageSearch,
  },
  {
    title: 'Razorpay Test Mode Payments',
    description: 'Checkout is wired into Razorpay Test Mode for a realistic but safe payment experience during evaluation.',
    icon: CreditCard,
  },
  {
    title: 'Full Audit Trail',
    description: 'Every AI-assisted decision is traceable so judges and merchants can see what the system did and why.',
    icon: FileText,
  },
  {
    title: 'Merchant Dashboard + AI Insights',
    description: 'Merchants get orders, revenue, inventory signals, and AI-generated growth ideas from live dashboard data.',
    icon: ChartColumnIncreasing,
  },
  {
    title: 'PDF Receipts',
    description: 'After successful payment, the buyer can download a proper receipt generated by the backend.',
    icon: ReceiptText,
  },
]

const architectureItems = [
  'React frontend for landing, catalog, cart, orders, logs, and merchant dashboard',
  'FastAPI backend for auth, products, carts, orders, receipts, and merchant APIs',
  'Custom AI agent loop with OpenRouter and tool-calling',
  'PostgreSQL-compatible SQLAlchemy data layer',
  'Razorpay Test Mode checkout and verification flow',
  'Audit log system for explainable AI interactions',
]

export const LandingPage: React.FC = () => {
  return (
    <div className="space-y-10 pb-8">
      <section className="relative overflow-hidden rounded-[2rem] border border-slate-200/70 bg-linear-to-br from-slate-950 via-blue-950 to-cyan-950 px-6 py-10 text-white shadow-xl sm:px-10 sm:py-14">
        <div className="absolute -left-10 top-8 h-40 w-40 rounded-full bg-cyan-400/20 blur-3xl" />
        <div className="absolute -right-8 bottom-4 h-48 w-48 rounded-full bg-blue-400/20 blur-3xl" />
        <div className="relative max-w-3xl space-y-5">
          <div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-cyan-100">
            <Sparkles className="h-3.5 w-3.5 text-cyan-300" />
            Built for Razorpay AI Buildathon - Track 1
          </div>
          <div className="space-y-3">
            <h1 className="max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">
              CampusGadgets AI Commerce
            </h1>
            <p className="max-w-2xl text-lg text-slate-200 sm:text-xl">
              AI-powered shopping plus merchant growth platform.
            </p>
            <p className="max-w-2xl text-sm leading-relaxed text-slate-300 sm:text-base">
              This project combines agentic buying assistance, secure checkout, explainable AI, and merchant intelligence in one end-to-end commerce experience.
            </p>
          </div>
          <div className="flex flex-wrap gap-3 pt-2">
            <Link
              to="/shop"
              className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950 transition-colors hover:bg-cyan-50"
            >
              Browse Products
            </Link>
            <Link
              to="/login"
              className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-bold text-white transition-colors hover:bg-white/15"
            >
              Login / Sign Up
            </Link>
          </div>
        </div>
      </section>

      <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
        <article className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-xs sm:p-8">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase tracking-wider text-slate-700">
            <Workflow className="h-3.5 w-3.5" />
            What is this project?
          </div>
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-950">
            A commerce system that helps buyers decide faster and helps merchants grow smarter.
          </h2>
          <p className="mt-4 text-sm leading-7 text-slate-600">
            Traditional ecommerce makes discovery slow for customers and leaves merchants with raw data but little guidance. CampusGadgets AI Commerce solves both sides: buyers get a conversational agent that can guide product discovery and purchase decisions, while merchants get a dedicated dashboard with sales visibility, inventory warnings, and AI-generated recommendations for revenue growth.
          </p>
        </article>

        <article className="rounded-3xl border border-cyan-100 bg-cyan-50/70 p-6 shadow-xs sm:p-8">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 text-xs font-bold uppercase tracking-wider text-cyan-800">
            <ShieldCheck className="h-3.5 w-3.5" />
            Why it matters
          </div>
          <p className="text-sm leading-7 text-cyan-950">
            Judges can quickly see the full product story: AI shopping, auditable decisions, payment integration, merchant analytics, and a realistic multi-role experience in one application.
          </p>
        </article>
      </section>

      <section className="space-y-5">
        <div>
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-950">Key Features</h2>
          <p className="mt-1 text-sm text-slate-500">Built to demonstrate both buyer-side intelligence and merchant-side growth operations.</p>
        </div>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {featureCards.map((feature) => {
            const Icon = feature.icon
            return (
              <article key={feature.title} className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-xs transition-colors hover:border-slate-300">
                <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-linear-to-br from-blue-600 to-cyan-500 text-white shadow-sm">
                  <Icon className="h-5 w-5" />
                </div>
                <h3 className="text-base font-bold text-slate-950">{feature.title}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-600">{feature.description}</p>
              </article>
            )
          })}
        </div>
      </section>

      <section className="grid gap-6 lg:grid-cols-2">
        <article className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-xs sm:p-8">
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-950">For Buyers</h2>
          <p className="mt-2 text-sm leading-7 text-slate-600">
            Buyers can explore the catalog openly, then use the AI assistant to narrow choices, understand tradeoffs, add items to a cart, complete Razorpay Test Mode checkout, and download a PDF receipt.
          </p>
          <div className="mt-5 flex flex-wrap gap-2 text-xs font-bold uppercase tracking-wider text-slate-500">
            <span className="rounded-full bg-slate-100 px-3 py-1">Browse</span>
            <span className="rounded-full bg-slate-100 px-3 py-1">Chat</span>
            <span className="rounded-full bg-slate-100 px-3 py-1">Add to cart</span>
            <span className="rounded-full bg-slate-100 px-3 py-1">Pay</span>
            <span className="rounded-full bg-slate-100 px-3 py-1">Get receipt</span>
          </div>
        </article>

        <article className="rounded-3xl border border-emerald-100 bg-emerald-50/70 p-6 shadow-xs sm:p-8">
          <h2 className="text-2xl font-extrabold tracking-tight text-emerald-950">For Merchants</h2>
          <p className="mt-2 text-sm leading-7 text-emerald-950/80">
            Merchants get a focused dashboard showing order count, revenue, product coverage, low-stock alerts, recent orders, and top-selling products. One click generates AI business insights with practical recommendations to improve conversion and grow revenue.
          </p>
        </article>
      </section>

      <section className="rounded-[2rem] border border-slate-200/80 bg-white p-6 shadow-xs sm:p-8">
        <div className="mb-5">
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-950">Architecture Overview</h2>
          <p className="mt-1 text-sm text-slate-500">A clean, judge-friendly snapshot of how the system is composed.</p>
        </div>
        <div className="grid gap-4 lg:grid-cols-[1fr_auto_1fr_auto_1fr]">
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Frontend</p>
            <p className="mt-2 text-sm font-semibold text-slate-900">React + Tailwind</p>
            <p className="mt-2 text-sm text-slate-600">Landing, shop, cart, orders, audit logs, merchant dashboard.</p>
          </div>
          <div className="hidden items-center justify-center text-slate-300 lg:flex">→</div>
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Backend</p>
            <p className="mt-2 text-sm font-semibold text-slate-900">FastAPI + SQLAlchemy</p>
            <p className="mt-2 text-sm text-slate-600">Auth, catalog, carts, orders, receipts, merchant APIs.</p>
          </div>
          <div className="hidden items-center justify-center text-slate-300 lg:flex">→</div>
          <div className="rounded-2xl border border-cyan-100 bg-cyan-50 p-4">
            <p className="text-xs font-bold uppercase tracking-wider text-cyan-700">AI + Payments</p>
            <p className="mt-2 text-sm font-semibold text-cyan-950">OpenRouter + Razorpay</p>
            <p className="mt-2 text-sm text-cyan-900/80">Tool-calling agent, merchant insights, Test Mode checkout.</p>
          </div>
        </div>
        <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          {architectureItems.map((item) => (
            <div key={item} className="rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm text-slate-700">
              {item}
            </div>
          ))}
        </div>
      </section>

      <section className="rounded-[2rem] border border-slate-200/80 bg-white p-6 shadow-xs sm:p-8">
        <div className="mb-5">
          <h2 className="text-2xl font-extrabold tracking-tight text-slate-950">How to Try It</h2>
          <p className="mt-1 text-sm text-slate-500">Use the seeded accounts below to explore both user roles.</p>
        </div>
        <div className="grid gap-4 lg:grid-cols-3">
          <article className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Customer 1</p>
            <p className="mt-3 text-sm font-semibold text-slate-900">alice@example.com</p>
            <p className="mt-1 text-sm text-slate-600">Password: alice-password</p>
          </article>
          <article className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Customer 2</p>
            <p className="mt-3 text-sm font-semibold text-slate-900">bob@example.com</p>
            <p className="mt-1 text-sm text-slate-600">Password: bob-password</p>
          </article>
          <article className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5">
            <p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Merchant</p>
            <p className="mt-3 text-sm font-semibold text-emerald-950">merchant@campusgadgets.com</p>
            <p className="mt-1 text-sm text-emerald-900/80">Password: merchant123</p>
          </article>
        </div>
        <div className="mt-5 rounded-3xl border border-slate-200 bg-slate-50 p-5">
          <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Quick steps</p>
          <p className="mt-3 text-sm leading-7 text-slate-700">
            Start at the shop to browse products. Sign in as a buyer to test cart, chat, checkout, and receipt flows. Sign in as the merchant to open the Merchant Dashboard and generate AI growth insights.
          </p>
        </div>
      </section>
    </div>
  )
}
